'use client';
import AdminFrame from '@/lib/AdminFrame';
import BridgeCollectionEditor from '@/lib/editorial/BridgeCollectionEditor';
export default function Page(){return <AdminFrame title="Edición · Pastoral" subtitle="Supabase → pastoral → CAMINO" badge="Puente editorial"><BridgeCollectionEditor table="pastoral_entities" title="Comunidades y entidades" subtitle="Raíz de horarios, eventos y avisos." appContract="CAMINO solo debe recibir horarios/eventos que apunten a entidades publicadas válidas." titleKey="name" secondaryKey="entity_type" orderBy="name" create={{keyStrategy:'prefixed-slug',keyPrefix:'pastoral-',slugSource:'name',slugField:'slug',buttonLabel:'Nueva entidad',defaults:{review_status:'draft',verified:false,revision:1}}} fields={[
{key:'name',label:'Nombre',required:true},{key:'subtitle',label:'Subtítulo'},{key:'entity_type',label:'Tipo',required:true,options:[{value:'parish',label:'Parroquia'},{value:'pastoral_cell',label:'Célula / comunidad pastoral'}]},{key:'diocese',label:'Diócesis'},{key:'diocese_id',label:'ID diócesis'},{key:'city',label:'Ciudad'},{key:'neighborhood',label:'Barrio'},{key:'address',label:'Dirección'},{key:'phone',label:'Teléfono'},{key:'email',label:'Correo'},{key:'website',label:'Web',type:'url'},{key:'latitude',label:'Latitud',type:'number'},{key:'longitude',label:'Longitud',type:'number'},{key:'verified',label:'Verificada',type:'boolean'},{key:'review_status',label:'Estado editorial',readOnly:true},{key:'revision',label:'Revisión',type:'number',readOnly:true},{key:'published_at',label:'Publicado',readOnly:true}
]}/><div className="manager-spacer"/><BridgeCollectionEditor table="pastoral_schedules" locale={null} title="Horarios" subtitle="Horarios públicos asociados a una entidad." appContract="entity_id debe corresponder a una entidad que CAMINO pueda sincronizar." titleKey="time_label" secondaryKey="schedule_type" orderBy="sort_order" create={{keyStrategy:'prefixed-uuid',keyPrefix:'schedule-',slugSource:'time_label',slugField:null,buttonLabel:'Nuevo horario',defaults:{review_status:'draft',verified:false,revision:1}}} fields={[
{key:'entity_id',label:'Entidad',required:true,help:'Selecciona la entidad pastoral asociada.',relation:{table:'pastoral_entities',labelKey:'name',secondaryKey:'entity_type',orderBy:'name'}},{key:'schedule_type',label:'Tipo',required:true,options:[{value:'mass',label:'Santa Misa'}]},{key:'day_of_week',label:'Día de semana',type:'number',options:[{value:0,label:'Domingo'},{value:1,label:'Lunes'},{value:2,label:'Martes'},{value:3,label:'Miércoles'},{value:4,label:'Jueves'},{value:5,label:'Viernes'},{value:6,label:'Sábado'}]},{key:'time_label',label:'Hora / etiqueta',required:true},{key:'notes',label:'Notas',type:'textarea'},{key:'sort_order',label:'Orden',type:'number'},{key:'verified',label:'Verificado',type:'boolean'},{key:'review_status',label:'Estado editorial',readOnly:true},{key:'revision',label:'Revisión',type:'number',readOnly:true},{key:'published_at',label:'Publicado',readOnly:true}
]}/><div className="manager-spacer"/><BridgeCollectionEditor table="pastoral_public_events" title="Eventos oficiales" subtitle="Agenda pública sincronizada por CAMINO." appContract="El evento necesita entity_id válido. push_requested solicita despacho por la infraestructura segura de Supabase; el admin no escribe directamente en outbox." titleKey="title" secondaryKey="starts_at" orderBy="starts_at" ascending={false} create={{keyStrategy:'prefixed-uuid',keyPrefix:'event-',slugSource:'title',slugField:null,buttonLabel:'Nuevo evento',defaults:{review_status:'draft',verified:false,revision:1,is_featured:false,priority:0,push_requested:false}}} fields={[
{key:'entity_id',label:'Entidad',required:true,help:'Selecciona la entidad responsable del evento.',relation:{table:'pastoral_entities',labelKey:'name',secondaryKey:'entity_type',orderBy:'name'}},{key:'title',label:'Título',required:true},{key:'starts_at',label:'Inicio',required:true},{key:'ends_at',label:'Final'},{key:'location',label:'Lugar'},{key:'event_type',label:'Tipo',required:true},{key:'description',label:'Descripción',type:'textarea'},{key:'is_featured',label:'Destacado',type:'boolean'},{key:'priority',label:'Prioridad',type:'number'},{key:'push_requested',label:'Solicitar push',type:'boolean'},{key:'verified',label:'Verificado',type:'boolean'},{key:'review_status',label:'Estado editorial',readOnly:true},{key:'revision',label:'Revisión',type:'number',readOnly:true},{key:'published_at',label:'Publicado',readOnly:true}
]}/><div className="manager-spacer"/><BridgeCollectionEditor table="pastoral_announcements" title="Avisos pastorales" subtitle="Avisos públicos con audiencia y vigencia." appContract="CAMINO filtra avisos publicados por audiencia. Si audience_scope es entity o diocese, sus IDs deben ser válidos." titleKey="title" secondaryKey="announcement_type" orderBy="updated_at" ascending={false} create={{keyStrategy:'prefixed-uuid',keyPrefix:'announcement-',slugSource:'title',slugField:null,buttonLabel:'Nuevo aviso',defaults:{review_status:'draft',verified:false,revision:1,is_featured:false,priority:0,push_requested:false}}} fields={[
{key:'title',label:'Título',required:true},{key:'body',label:'Contenido',type:'textarea',required:true},{key:'announcement_type',label:'Tipo',required:true,options:[{value:'info',label:'Información pastoral'}]},{key:'audience_scope',label:'Audiencia',required:true,options:[{value:'global',label:'Toda la comunidad CAMINO'},{value:'entity',label:'Entidad pastoral específica'},{value:'diocese',label:'Diócesis específica'}]},{key:'diocese_id',label:'Diócesis ID'},{key:'entity_id',label:'Entidad',help:'Opcional. Selecciona una entidad cuando la audiencia sea específica.',relation:{table:'pastoral_entities',labelKey:'name',secondaryKey:'entity_type',orderBy:'name'}},{key:'starts_at',label:'Inicio'},{key:'expires_at',label:'Vence'},{key:'priority',label:'Prioridad',type:'number'},{key:'is_featured',label:'Destacado',type:'boolean'},{key:'action_label',label:'Texto de acción'},{key:'action_href',label:'Enlace'},{key:'push_requested',label:'Solicitar push',type:'boolean'},{key:'verified',label:'Verificado',type:'boolean'},{key:'review_status',label:'Estado editorial',readOnly:true},{key:'revision',label:'Revisión',type:'number',readOnly:true},{key:'published_at',label:'Publicado',readOnly:true}
]}/></AdminFrame>}
